#!/bin/bash
cd "$(dirname "$0")"
source ./script/setup.sh

# 1. It takes 300ms for cmd-help to generate. It's too long to run in build-debug.sh, that's why we ignore it
# 2. Grammar is not expected to change very often, that's why it's not regenerated by default
./generate.sh --ignore-xcodeproj --ignore-cmd-help --ignore-shell-parser
swift build "$@"
swift build --target AppBundleTests "$@" # swift build doesn't build test targets by default :(

# mur — preserve .debug/MurApp.app across rebuilds so the macOS
# Accessibility grant doesn't get torn down every iteration. The bundle
# id `bobko.aerospace.debug` plus a stable wrapper structure means
# Accessibility only needs to be re-granted when the binary signature
# actually changes (and only that, not on every clean wipe).
mkdir -p .debug
cp .build/debug/mur .debug/mur

mkdir -p .debug/MurApp.app/Contents/MacOS
cp .build/debug/MurApp .debug/MurApp.app/Contents/MacOS/MurApp
if ! test -f .debug/MurApp.app/Contents/Info.plist; then
    cat > .debug/MurApp.app/Contents/Info.plist <<'EOF'
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
    <key>CFBundleExecutable</key>          <string>MurApp</string>
    <key>CFBundleIdentifier</key>          <string>bobko.aerospace.debug</string>
    <key>CFBundleName</key>                <string>MurApp</string>
    <key>CFBundleDisplayName</key>         <string>mur (debug)</string>
    <key>CFBundleShortVersionString</key>  <string>0.0.0-SNAPSHOT</string>
    <key>CFBundleVersion</key>             <string>0.0.0</string>
    <key>CFBundlePackageType</key>         <string>APPL</string>
    <key>LSMinimumSystemVersion</key>      <string>13.0</string>
    <key>LSUIElement</key>                 <true/>
    <key>NSPrincipalClass</key>            <string>NSApplication</string>
    <key>NSHighResolutionCapable</key>     <true/>
</dict>
</plist>
EOF
fi
codesign --force --deep --sign - .debug/MurApp.app > /dev/null 2>&1 || true
